version: '3.8'

networks:
  dia_fr_api_dev_net:
    driver: bridge

services:
  cronjob-service:
    image: $IMAGE_NAME/cronjob-service:$VERSION
    container_name: $DOMAIN.API.cronjob-service
    command: bash -c "python main.py"
    volumes:
      - ../../../cronjob/:/app/
    

    networks:
      - dia_fr_api_dev_net
